// This file centralizes the definition of all available tools, organized by category.
export const categories = [
  {
    name: '热门工具',
    tools: [
      {
        id: 'merge',
        name: '合并 PDF',
        icon: 'combine',
        subtitle: '将多个 PDF 合并为一个文件。',
      },
      {
        id: 'split',
        name: '拆分 PDF',
        icon: 'scissors',
        subtitle: '按页范围提取为新的 PDF。',
      },
      {
        id: 'compress',
        name: '压缩 PDF',
        icon: 'zap',
        subtitle: '减小 PDF 文件大小。',
      },
      {
        id: 'edit',
        name: 'PDF 编辑器',
        icon: 'pocket-knife',
        subtitle:
          '在 PDF 上标注、高亮、涂黑、评论、添加形状/图片、搜索和查看。',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG 转 PDF',
        icon: 'image-up',
        subtitle: '将一张或多张 JPG 图片生成 PDF。',
      },
      {
        id: 'sign-pdf',
        name: '签署 PDF',
        icon: 'pen-tool',
        subtitle: '手写、输入或上传你的签名。',
      },
      {
        id: 'cropper',
        name: '裁剪 PDF',
        icon: 'crop',
        subtitle: '裁剪 PDF 每一页的页边距。',
      },
      {
        id: 'extract-pages',
        name: '提取页面',
        icon: 'ungroup',
        subtitle: '将选定页面保存为新文件。',
      },
      {
        id: 'duplicate-organize',
        name: '复制与整理',
        icon: 'files',
        subtitle: '复制、重排和删除页面。',
      },
      {
        id: 'delete-pages',
        name: '删除页面',
        icon: 'trash-2',
        subtitle: '删除文档中的指定页面。',
      },
    ],
  },
  {
    name: '编辑与标注',
    tools: [
      {
        id: 'edit',
        name: 'PDF 编辑器',
        icon: 'pocket-knife',
        subtitle:
          '在 PDF 上标注、高亮、涂黑、评论、添加形状/图片、搜索和查看。',
      },
      // { id: 'crop', name: 'Crop PDF', icon: 'crop', subtitle: 'Trim the margins of every page in your PDF.' },
      {
        id: 'add-page-numbers',
        name: '页码',
        icon: 'list-ordered',
        subtitle: '为文档添加页码。',
      },
      {
        id: 'add-watermark',
        name: '添加水印',
        icon: 'droplets',
        subtitle: '在 PDF 页面上叠加文本或图像水印。',
      },
      {
        id: 'add-header-footer',
        name: '页眉与页脚',
        icon: 'pilcrow',
        subtitle: '在页面顶部和底部添加文本。',
      },
      {
        id: 'invert-colors',
        name: '反相颜色',
        icon: 'contrast',
        subtitle: '创建 PDF 的“深色模式”版本。',
      },
      {
        id: 'change-background-color',
        name: '背景颜色',
        icon: 'palette',
        subtitle: '更改 PDF 的背景颜色。',
      },
      {
        id: 'change-text-color',
        name: '更改文本颜色',
        icon: 'type',
        subtitle: '更改 PDF 中文本的颜色。',
      },
      {
        id: 'sign-pdf',
        name: '签署 PDF',
        icon: 'pen-tool',
        subtitle: '手写、输入或上传你的签名。',
      },
      {
        id: 'remove-annotations',
        name: '移除注释',
        icon: 'eraser',
        subtitle: '移除评论、高亮和链接。',
      },
      {
        id: 'cropper',
        name: '裁剪 PDF',
        icon: 'crop',
        subtitle: '裁剪 PDF 每一页的页边距。',
      },
      {
        id: 'form-filler',
        name: 'PDF 表单填写',
        icon: 'square-pen',
        subtitle: '在浏览器中直接填写表单。',
      },
      {
        id: 'remove-blank-pages',
        name: '删除空白页',
        icon: 'file-minus-2',
        subtitle: '自动检测并删除空白页。',
      },
    ],
  },
  {
    name: '转换为 PDF',
    tools: [
      {
        id: 'image-to-pdf',
        name: '图片转 PDF',
        icon: 'images',
        subtitle: '将多种图片合并为一个 PDF。',
      },
      {
        id: 'jpg-to-pdf',
        name: 'JPG 转 PDF',
        icon: 'image-up',
        subtitle: '将一张或多张 JPG 图片生成 PDF。',
      },
      {
        id: 'png-to-pdf',
        name: 'PNG 转 PDF',
        icon: 'image-up',
        subtitle: '将一张或多张 PNG 图片生成 PDF。',
      },
      {
        id: 'webp-to-pdf',
        name: 'WebP 转 PDF',
        icon: 'image-up',
        subtitle: '将一张或多张 WebP 图片生成 PDF。',
      },
      {
        id: 'svg-to-pdf',
        name: 'SVG 转 PDF',
        icon: 'pen-tool',
        subtitle: '将一张或多张 SVG 图片生成 PDF。',
      },
      {
        id: 'bmp-to-pdf',
        name: 'BMP 转 PDF',
        icon: 'image',
        subtitle: '将一张或多张 BMP 图片生成 PDF。',
      },
      {
        id: 'heic-to-pdf',
        name: 'HEIC 转 PDF',
        icon: 'smartphone',
        subtitle: '将一张或多张 HEIC 图片生成 PDF。',
      },
      {
        id: 'tiff-to-pdf',
        name: 'TIFF 转 PDF',
        icon: 'layers',
        subtitle: '将一张或多张 TIFF 图片生成 PDF。',
      },
      {
        id: 'txt-to-pdf',
        name: '文本转 PDF',
        icon: 'file-pen',
        subtitle: '将纯文本文件转换为 PDF。',
      },
      // { id: 'md-to-pdf', name: 'Markdown to PDF', icon: 'file-text', subtitle: 'Convert a Markdown file into a PDF.' },
      // { id: 'scan-to-pdf', name: 'Scan to PDF', icon: 'camera', subtitle: 'Use your camera to create a scanned PDF.' },
      // { id: 'word-to-pdf', name: 'Word to PDF', icon: 'file-text', subtitle: 'Convert .docx documents to PDF.' },
    ],
  },
  {
    name: '从 PDF 转换',
    tools: [
      {
        id: 'pdf-to-jpg',
        name: 'PDF 转 JPG',
        icon: 'file-image',
        subtitle: '将每页转换为 JPG 图片。',
      },
      {
        id: 'pdf-to-png',
        name: 'PDF 转 PNG',
        icon: 'file-image',
        subtitle: '将每页转换为 PNG 图片。',
      },
      {
        id: 'pdf-to-webp',
        name: 'PDF 转 WebP',
        icon: 'file-image',
        subtitle: '将每页转换为 WebP 图片。',
      },
      {
        id: 'pdf-to-bmp',
        name: 'PDF 转 BMP',
        icon: 'file-image',
        subtitle: '将每页转换为 BMP 图片。',
      },
      {
        id: 'pdf-to-tiff',
        name: 'PDF 转 TIFF',
        icon: 'file-image',
        subtitle: '将每页转换为 TIFF 图片。',
      },
      {
        id: 'pdf-to-greyscale',
        name: 'PDF 转灰度',
        icon: 'palette',
        subtitle: '将所有颜色转换为黑白。',
      },
      // { id: 'pdf-to-markdown', name: 'PDF to Markdown', icon: 'file-pen', subtitle: 'Extract text into a Markdown file.' },
    ],
  },
  {
    name: '整理与管理',
    tools: [
      {
        id: 'ocr-pdf',
        name: 'OCR 文本识别',
        icon: 'scan-text',
        subtitle: '使 PDF 可搜索、可复制。',
      },
      {
        id: 'merge',
        name: '合并 PDF',
        icon: 'combine',
        subtitle: '将多个 PDF 合并为一个文件。',
      },
      {
        id: 'alternate-merge',
        name: '交替合并页面',
        icon: 'shuffle',
        subtitle: '通过交替页面合并 PDF。',
      },
      {
        id: 'organize',
        name: '整理 PDF',
        icon: 'grip',
        subtitle: '拖拽页面以重新排序。',
      },
      {
        id: 'duplicate-organize',
        name: '复制与整理',
        icon: 'files',
        subtitle: '复制、重排和删除页面。',
      },
      {
        id: 'split',
        name: '拆分 PDF',
        icon: 'scissors',
        subtitle: '按页范围提取为新的 PDF。',
      },
      {
        id: 'split-in-half',
        name: '分页切割',
        icon: 'table-columns-split',
        subtitle: '水平或垂直拆分页面。',
      },
      {
        id: 'extract-pages',
        name: '提取页面',
        icon: 'ungroup',
        subtitle: '将选定页面保存为新文件。',
      },
      {
        id: 'delete-pages',
        name: '删除页面',
        icon: 'trash-2',
        subtitle: '删除文档中的指定页面。',
      },
      {
        id: 'add-blank-page',
        name: '添加空白页',
        icon: 'file-plus-2',
        subtitle: '在任意位置插入空白页。',
      },
      {
        id: 'reverse-pages',
        name: '倒序页面',
        icon: 'arrow-down-z-a',
        subtitle: '反转文档中所有页面的顺序。',
      },
      {
        id: 'rotate',
        name: '旋转 PDF',
        icon: 'rotate-cw',
        subtitle: '以 90° 为步进旋转页面。',
      },
      {
        id: 'n-up',
        name: 'N-合一 PDF',
        icon: 'layout-grid',
        subtitle: '将多页排布到一张纸上。',
      },
      {
        id: 'combine-single-page',
        name: '合并为单页',
        icon: 'unfold-vertical',
        subtitle: '将所有页面拼接成一页长图。',
      },
      {
        id: 'view-metadata',
        name: '查看元数据',
        icon: 'info',
        subtitle: '查看 PDF 的隐藏属性。',
      },
      {
        id: 'edit-metadata',
        name: '编辑元数据',
        icon: 'file-cog',
        subtitle: '更改作者、标题等属性。',
      },
      {
        id: 'pdf-to-zip',
        name: 'PDF 打包为 ZIP',
        icon: 'stretch-horizontal',
        subtitle: '将多个 PDF 打包为一个 ZIP。',
      },
      {
        id: 'compare-pdfs',
        name: '比较 PDF',
        icon: 'git-compare',
        subtitle: '并排比较两个 PDF。',
      },
      {
        id: 'posterize',
        name: '海报拆分',
        icon: 'layout-grid',
        subtitle: '将大页面拆分成多页。',
      },
    ],
  },
  {
    name: '优化与修复',
    tools: [
      {
        id: 'compress',
        name: '压缩 PDF',
        icon: 'zap',
        subtitle: '减小 PDF 文件大小。',
      },
      {
        id: 'fix-dimensions',
        name: '统一页面大小',
        icon: 'ruler-dimension-line',
        subtitle: '将所有页面统一为一致的尺寸。',
      },
      {
        id: 'page-dimensions',
        name: '页面尺寸',
        icon: 'ruler',
        subtitle: '分析页面大小、方向和单位。',
      },
    ],
  },
  {
    name: 'PDF 安全',
    tools: [
      {
        id: 'encrypt',
        name: '加密 PDF',
        icon: 'lock',
        subtitle: '为 PDF 添加密码保护。',
      },
      {
        id: 'decrypt',
        name: '解密 PDF',
        icon: 'unlock',
        subtitle: '移除 PDF 密码保护。',
      },
      {
        id: 'flatten',
        name: '扁平化 PDF',
        icon: 'layers',
        subtitle: '将表单字段和注释转换为不可编辑。',
      },
      {
        id: 'remove-metadata',
        name: '移除元数据',
        icon: 'file-x',
        subtitle: '移除 PDF 中的隐藏数据。',
      },
      {
        id: 'change-permissions',
        name: '更改权限',
        icon: 'shield-check',
        subtitle: '设置或更改 PDF 的用户权限。',
      },
    ],
  },
];
